[2024-07-03T19:16:09.697+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T19:16:09.728+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-07-06T00:00:00+00:00 [queued]>
[2024-07-03T19:16:09.737+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-07-06T00:00:00+00:00 [queued]>
[2024-07-03T19:16:09.738+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-07-03T19:16:09.805+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): first_task> on 2023-07-06 00:00:00+00:00
[2024-07-03T19:16:09.811+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=792) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T19:16:09.813+0000] {standard_task_runner.py:63} INFO - Started process 801 to run task
[2024-07-03T19:16:09.813+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'scheduled__2023-07-06T00:00:00+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpsg0kxmz3']
[2024-07-03T19:16:09.814+0000] {standard_task_runner.py:91} INFO - Job 133: Subtask first_task
[2024-07-03T19:16:09.873+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag.first_task scheduled__2023-07-06T00:00:00+00:00 [running]> on host 2a6e93921527
[2024-07-03T19:16:09.971+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-06T00:00:00+00:00'
[2024-07-03T19:16:09.972+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T19:16:09.986+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-03T19:16:09.987+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'Hello world, this is the first task']
[2024-07-03T19:16:10.001+0000] {subprocess.py:86} INFO - Output:
[2024-07-03T19:16:10.003+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: Hello: command not found
[2024-07-03T19:16:10.004+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-07-03T19:16:10.005+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T19:16:10.018+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-07-03T19:16:10.022+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, run_id=scheduled__2023-07-06T00:00:00+00:00, execution_date=20230706T000000, start_date=20240703T191609, end_date=20240703T191610
[2024-07-03T19:16:10.039+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 133 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 801)
[2024-07-03T19:16:10.070+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T19:16:10.080+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-03T19:20:58.469+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T19:20:58.501+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-07-06T00:00:00+00:00 [queued]>
[2024-07-03T19:20:58.512+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-07-06T00:00:00+00:00 [queued]>
[2024-07-03T19:20:58.513+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-07-03T19:20:58.583+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): first_task> on 2023-07-06 00:00:00+00:00
[2024-07-03T19:20:58.591+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=952) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T19:20:58.592+0000] {standard_task_runner.py:63} INFO - Started process 961 to run task
[2024-07-03T19:20:58.592+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'scheduled__2023-07-06T00:00:00+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpqu69tbo0']
[2024-07-03T19:20:58.594+0000] {standard_task_runner.py:91} INFO - Job 165: Subtask first_task
[2024-07-03T19:20:58.662+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag.first_task scheduled__2023-07-06T00:00:00+00:00 [running]> on host 2a6e93921527
[2024-07-03T19:20:58.766+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-06T00:00:00+00:00'
[2024-07-03T19:20:58.767+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T19:20:58.789+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-03T19:20:58.798+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'Hello world, this is the first task']
[2024-07-03T19:20:58.819+0000] {subprocess.py:86} INFO - Output:
[2024-07-03T19:20:58.821+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: Hello: command not found
[2024-07-03T19:20:58.822+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-07-03T19:20:58.823+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T19:20:58.835+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-07-03T19:20:58.840+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, run_id=scheduled__2023-07-06T00:00:00+00:00, execution_date=20230706T000000, start_date=20240703T192058, end_date=20240703T192058
[2024-07-03T19:20:58.858+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 165 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 961)
[2024-07-03T19:20:58.888+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T19:20:58.897+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
