[2024-07-03T19:31:06.131+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T19:31:06.175+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-07-15T00:00:00+00:00 [queued]>
[2024-07-03T19:31:06.197+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-07-15T00:00:00+00:00 [queued]>
[2024-07-03T19:31:06.198+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 6
[2024-07-03T19:31:06.222+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): first_task> on 2023-07-15 00:00:00+00:00
[2024-07-03T19:31:06.230+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1343) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T19:31:06.232+0000] {standard_task_runner.py:63} INFO - Started process 1360 to run task
[2024-07-03T19:31:06.232+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'scheduled__2023-07-15T00:00:00+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp2sdtojh_']
[2024-07-03T19:31:06.234+0000] {standard_task_runner.py:91} INFO - Job 252: Subtask first_task
[2024-07-03T19:31:06.364+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag.first_task scheduled__2023-07-15T00:00:00+00:00 [running]> on host 2a6e93921527
[2024-07-03T19:31:06.488+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-15T00:00:00+00:00'
[2024-07-03T19:31:06.489+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T19:31:06.510+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-03T19:31:06.513+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'Hello world, this is the first task']
[2024-07-03T19:31:06.530+0000] {subprocess.py:86} INFO - Output:
[2024-07-03T19:31:06.532+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: Hello: command not found
[2024-07-03T19:31:06.533+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-07-03T19:31:06.534+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T19:31:06.549+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-07-03T19:31:06.555+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=first_dag, task_id=first_task, run_id=scheduled__2023-07-15T00:00:00+00:00, execution_date=20230715T000000, start_date=20240703T193106, end_date=20240703T193106
[2024-07-03T19:31:06.577+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 252 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 1360)
[2024-07-03T19:31:06.616+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T19:31:06.640+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:31:06.643+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
