[2024-07-03T19:31:06.574+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T19:31:06.605+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-07-14T00:00:00+00:00 [queued]>
[2024-07-03T19:31:06.617+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-07-14T00:00:00+00:00 [queued]>
[2024-07-03T19:31:06.618+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 6
[2024-07-03T19:31:06.636+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): first_task> on 2023-07-14 00:00:00+00:00
[2024-07-03T19:31:06.646+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1355) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T19:31:06.648+0000] {standard_task_runner.py:63} INFO - Started process 1366 to run task
[2024-07-03T19:31:06.648+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'scheduled__2023-07-14T00:00:00+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp5cvvbigz']
[2024-07-03T19:31:06.650+0000] {standard_task_runner.py:91} INFO - Job 255: Subtask first_task
[2024-07-03T19:31:06.713+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag.first_task scheduled__2023-07-14T00:00:00+00:00 [running]> on host 2a6e93921527
[2024-07-03T19:31:06.807+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-14T00:00:00+00:00'
[2024-07-03T19:31:06.808+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T19:31:06.824+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-03T19:31:06.825+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'Hello world, this is the first task']
[2024-07-03T19:31:06.839+0000] {subprocess.py:86} INFO - Output:
[2024-07-03T19:31:06.841+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: Hello: command not found
[2024-07-03T19:31:06.842+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-07-03T19:31:06.843+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T19:31:06.855+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-07-03T19:31:06.861+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=first_dag, task_id=first_task, run_id=scheduled__2023-07-14T00:00:00+00:00, execution_date=20230714T000000, start_date=20240703T193106, end_date=20240703T193106
[2024-07-03T19:31:06.879+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 255 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 1366)
[2024-07-03T19:31:06.902+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T19:31:06.923+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:31:06.926+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
