[2024-07-03T19:25:01.444+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T19:25:01.482+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-07-03T00:00:00+00:00 [queued]>
[2024-07-03T19:25:01.493+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-07-03T00:00:00+00:00 [queued]>
[2024-07-03T19:25:01.494+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 6
[2024-07-03T19:25:01.599+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): first_task> on 2023-07-03 00:00:00+00:00
[2024-07-03T19:25:01.606+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1094) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T19:25:01.608+0000] {standard_task_runner.py:63} INFO - Started process 1110 to run task
[2024-07-03T19:25:01.611+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'scheduled__2023-07-03T00:00:00+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpfu9mpz8_']
[2024-07-03T19:25:01.613+0000] {standard_task_runner.py:91} INFO - Job 194: Subtask first_task
[2024-07-03T19:25:01.687+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag.first_task scheduled__2023-07-03T00:00:00+00:00 [running]> on host 2a6e93921527
[2024-07-03T19:25:01.814+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-03T00:00:00+00:00'
[2024-07-03T19:25:01.815+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T19:25:01.831+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-03T19:25:01.833+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'Hello world, this is the first task']
[2024-07-03T19:25:01.847+0000] {subprocess.py:86} INFO - Output:
[2024-07-03T19:25:01.850+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: Hello: command not found
[2024-07-03T19:25:01.851+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-07-03T19:25:01.854+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T19:25:01.869+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-07-03T19:25:01.875+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, run_id=scheduled__2023-07-03T00:00:00+00:00, execution_date=20230703T000000, start_date=20240703T192501, end_date=20240703T192501
[2024-07-03T19:25:01.897+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 194 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 1110)
[2024-07-03T19:25:01.943+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T19:25:01.968+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:25:01.973+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
