[2024-07-03T19:03:59.762+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T19:03:59.804+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2021-07-10T00:00:00+00:00 [queued]>
[2024-07-03T19:03:59.822+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2021-07-10T00:00:00+00:00 [queued]>
[2024-07-03T19:03:59.823+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 6
[2024-07-03T19:03:59.842+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): first_task> on 2021-07-10 00:00:00+00:00
[2024-07-03T19:03:59.849+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=538) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T19:03:59.851+0000] {standard_task_runner.py:63} INFO - Started process 557 to run task
[2024-07-03T19:03:59.853+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'scheduled__2021-07-10T00:00:00+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpv3wvfkyt']
[2024-07-03T19:03:59.854+0000] {standard_task_runner.py:91} INFO - Job 104: Subtask first_task
[2024-07-03T19:03:59.905+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag.first_task scheduled__2021-07-10T00:00:00+00:00 [running]> on host 2a6e93921527
[2024-07-03T19:03:59.987+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2021-07-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-07-10T00:00:00+00:00'
[2024-07-03T19:03:59.988+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T19:04:00.000+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-03T19:04:00.001+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'Hello world, this is the first task']
[2024-07-03T19:04:00.013+0000] {subprocess.py:86} INFO - Output:
[2024-07-03T19:04:00.015+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: Hello: command not found
[2024-07-03T19:04:00.015+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-07-03T19:04:00.016+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T19:04:00.027+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-07-03T19:04:00.031+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, run_id=scheduled__2021-07-10T00:00:00+00:00, execution_date=20210710T000000, start_date=20240703T190359, end_date=20240703T190400
[2024-07-03T19:04:00.045+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 104 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 557)
[2024-07-03T19:04:00.065+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T19:04:00.080+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T19:04:00.082+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
