[2024-07-03T19:18:11.177+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T19:18:11.203+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-07-10T00:00:00+00:00 [queued]>
[2024-07-03T19:18:11.213+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-07-10T00:00:00+00:00 [queued]>
[2024-07-03T19:18:11.214+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-07-03T19:18:11.232+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): first_task> on 2023-07-10 00:00:00+00:00
[2024-07-03T19:18:11.239+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=880) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T19:18:11.240+0000] {standard_task_runner.py:63} INFO - Started process 890 to run task
[2024-07-03T19:18:11.241+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'scheduled__2023-07-10T00:00:00+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp2vt45xaj']
[2024-07-03T19:18:11.242+0000] {standard_task_runner.py:91} INFO - Job 153: Subtask first_task
[2024-07-03T19:18:11.293+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag.first_task scheduled__2023-07-10T00:00:00+00:00 [running]> on host 2a6e93921527
[2024-07-03T19:18:11.391+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-10T00:00:00+00:00'
[2024-07-03T19:18:11.392+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T19:18:11.406+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-03T19:18:11.407+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'Hello world, this is the first task']
[2024-07-03T19:18:11.419+0000] {subprocess.py:86} INFO - Output:
[2024-07-03T19:18:11.421+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: Hello: command not found
[2024-07-03T19:18:11.422+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-07-03T19:18:11.422+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T19:18:11.434+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-07-03T19:18:11.438+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, run_id=scheduled__2023-07-10T00:00:00+00:00, execution_date=20230710T000000, start_date=20240703T191811, end_date=20240703T191811
[2024-07-03T19:18:11.455+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 153 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 890)
[2024-07-03T19:18:11.495+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T19:18:11.505+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-03T19:23:00.172+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T19:23:00.209+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-07-10T00:00:00+00:00 [queued]>
[2024-07-03T19:23:00.223+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.first_task scheduled__2023-07-10T00:00:00+00:00 [queued]>
[2024-07-03T19:23:00.224+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-07-03T19:23:00.249+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): first_task> on 2023-07-10 00:00:00+00:00
[2024-07-03T19:23:00.261+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1028) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T19:23:00.268+0000] {standard_task_runner.py:63} INFO - Started process 1041 to run task
[2024-07-03T19:23:00.269+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'first_task', 'scheduled__2023-07-10T00:00:00+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpcf31two2']
[2024-07-03T19:23:00.270+0000] {standard_task_runner.py:91} INFO - Job 184: Subtask first_task
[2024-07-03T19:23:00.357+0000] {task_command.py:426} INFO - Running <TaskInstance: first_dag.first_task scheduled__2023-07-10T00:00:00+00:00 [running]> on host 2a6e93921527
[2024-07-03T19:23:00.504+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-10T00:00:00+00:00'
[2024-07-03T19:23:00.507+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T19:23:00.527+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-03T19:23:00.529+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'Hello world, this is the first task']
[2024-07-03T19:23:00.558+0000] {subprocess.py:86} INFO - Output:
[2024-07-03T19:23:00.560+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: Hello: command not found
[2024-07-03T19:23:00.561+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-07-03T19:23:00.562+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T19:23:00.580+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-07-03T19:23:00.589+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, run_id=scheduled__2023-07-10T00:00:00+00:00, execution_date=20230710T000000, start_date=20240703T192300, end_date=20240703T192300
[2024-07-03T19:23:00.638+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 184 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 1041)
[2024-07-03T19:23:00.691+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T19:23:00.705+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
